  struct Array arr = {{4, 6, 9, 13, 17, 25, 67}, 10, 6};
    // cout << BinerySearch(0, arr.length, 25, arr) << endl;
    // cout << RBinerySearch(0, arr.length, 25, arr) << endl;
    // cout << Max(arr) << endl;
    // cout << Min(arr) << endl;
    // cout << Sum(arr) << endl;
    // cout << Sum(arr) / arr.length << endl;
    // display(arr);
    // reverse(arr);
    // display(arr);
    // reverse2(&arr);
    // display(arr);
    // insert(23, arr);
    // display(arr);
    // cout << CSort(arr) << endl;